#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{ if .Values.fuse.enabled -}}

{{- $name := include "alluxio.name" . }}
{{- $fullName := include "alluxio.fullname" . }}
{{- $chart := include "alluxio.chart" . }}
{{- $hostMountPath := include "alluxio.mount.basePath" "" }}
{{- $alluxioFuseMountPoint := include "alluxio.mount.basePath" "/fuse" }}

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $fullName }}-fuse
  labels:
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: alluxio-fuse
spec:
  selector:
    matchLabels:
      app: {{ $name }}
      chart: {{ $chart }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: alluxio-fuse
  template:
    metadata:
      labels:
        app: {{ $name }}
        chart: {{ $chart }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: alluxio-fuse
      annotations:
      {{- if .Values.fuse.podAnnotations }}
{{- toYaml .Values.fuse.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if and .Values.metrics.prometheusMetricsServlet.enabled .Values.metrics.prometheusMetricsServlet.podAnnotations }}
{{- toYaml .Values.metrics.prometheusMetricsServlet.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      nodeSelector:
      {{- if .Values.fuse.nodeSelector }}
{{ toYaml .Values.fuse.nodeSelector | trim | indent 8  }}
      {{- end }}
      {{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | trim | indent 8  }}
      {{- end }}
      affinity:
      {{- if .Values.fuse.affinity }}
{{- toYaml .Values.fuse.affinity | indent 8 }}
      {{- end }}
      tolerations:
      {{- if .Values.fuse.tolerations }}
{{ toYaml .Values.fuse.tolerations | trim | indent 8  }}
      {{- end }}
      {{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | trim | indent 8  }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.user }}
        runAsGroup: {{ .Values.group }}
        fsGroup: {{ .Values.fsGroup }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
{{ include "alluxio.imagePullSecrets" . | indent 6 }}
      {{- end}}
      initContainers:
        - name: wait-master
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          command: ["/bin/sh", "-c"]
          args:
            - until nslookup {{ $fullName }}-master-0;
              do sleep 2;
              done
          volumeMounts:
          - name: {{ $fullName }}-alluxio-conf
            mountPath: /opt/alluxio/conf
      containers:
        - name: alluxio-fuse
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
          {{- if .Values.fuse.resources }}
{{ include "alluxio.resources" .Values.fuse.resources | indent 10 }}
          {{- end }}
          command: ["/entrypoint.sh"]
          args:
            - fuse
            - {{ required "The path of the dataset must be set." .Values.dataset.path }}
            - {{ $alluxioFuseMountPoint }}
            {{- range .Values.fuse.mountOptions }}
            - -o {{ . }}
            {{- end }}
          env:
            - name: ALLUXIO_CLIENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- range $key, $value := .Values.fuse.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          securityContext:
            privileged: true # required by bidirectional mount
          lifecycle:
            preStop:
              exec:
                command: ["/opt/alluxio/integration/fuse/bin/alluxio-fuse", "unmount", {{ $alluxioFuseMountPoint }}]
          volumeMounts:
            - name: alluxio-fuse-mount
              mountPath: {{ $hostMountPath }}
              mountPropagation: Bidirectional
            - name: {{ $fullName }}-alluxio-conf
              mountPath: /opt/alluxio/conf
            {{- if .Values.secrets }}
{{- include "alluxio.volumeMounts" (dict "volumeMounts" .Values.secrets.fuse "readOnly" true) | indent 12 }}
            {{- end }}
            {{- if .Values.configMaps }}
{{- include "alluxio.volumeMounts" (dict "volumeMounts" .Values.configMaps.fuse "readOnly" true) | indent 12 }}
            {{- end }}
            {{- if .Values.pvcMounts }}
{{- include "alluxio.volumeMounts" (dict "volumeMounts" .Values.pvcMounts.fuse "readOnly" false) | indent 12 }}
            {{- end }}
      restartPolicy: Always
      volumes:
        - name: alluxio-fuse-mount
          hostPath:
            path: {{ $hostMountPath }}
            type: DirectoryOrCreate
        - name: {{ $fullName }}-alluxio-conf
          configMap:
            name: {{ $fullName }}-alluxio-conf
        {{- if .Values.secrets }}
{{- include "alluxio.secretVolumes" .Values.secrets.fuse | indent 8 }}
        {{- end }}
        {{- if .Values.configMaps }}
{{- include "alluxio.configMapVolumes" .Values.configMaps.fuse | indent 8 }}
        {{- end }}
        {{- if .Values.pvcMounts }}
{{- include "alluxio.persistentVolumeClaims" .Values.pvcMounts.fuse | indent 8 }}
        {{- end }}
{{- end }}
