#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{ if .Values.csi.enabled -}}
{{- $name := include "alluxio.name" . }}
{{- $fullName := include "alluxio.fullname" . }}
{{- $chart := include "alluxio.chart" . }}

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $fullName }}-fuse-config
  labels:
    name: {{ $fullName }}-csi-fuse-config
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  alluxio-fuse-config: |
    kind: Pod
    apiVersion: v1
    metadata:
      name: {{ $fullName }}-fuse
      labels:
        name: {{ $fullName }}-fuse
        app: {{ $name }}
        role: alluxio-fuse
      annotations:
      {{- if .Values.fuse.podAnnotations }}
{{- toYaml .Values.fuse.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if and .Values.metrics.PrometheusMetricsServlet.enabled .Values.metrics.PrometheusMetricsServlet.podAnnotations }}
{{- toYaml .Values.metrics.PrometheusMetricsServlet.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      nodeName:
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy | default (.Values.hostNetwork | ternary "ClusterFirstWithHostNet" "ClusterFirst") }}
      nodeSelector:
        {{- if .Values.fuse.nodeSelector }}
{{ toYaml .Values.fuse.nodeSelector | trim | indent 8 }}
        {{- end }}
        {{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | trim | indent 8 }}
        {{- end }}
      affinity:
      {{- if .Values.fuse.affinity }}
{{- toYaml .Values.fuse.affinity | indent 8 }}
      {{- end }}
      tolerations:
        {{- if .Values.fuse.tolerations }}
{{ toYaml .Values.fuse.tolerations | trim | indent 8 }}
        {{- end }}
        {{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | trim | indent 8 }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
{{ include "alluxio.imagePullSecrets" . | indent 6 }}
      {{- end}}
      initContainers:
        - name: wait-master
          image: busybox:stable
          command: ["/bin/sh", "-c"]
          args:
            - until nslookup {{ $fullName }}-master-0;
              do sleep 2;
              done
      containers:
        - name: alluxio-fuse
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.fuse.resources }}
{{ include "alluxio.resources" .Values.fuse.resources | indent 10 }}
          {{- end }}
          command: [ "integration/fuse/bin/alluxio-fuse" ]
          args:
            - mount
            {{- if not (get .Values.properties "alluxio.dora.client.ufs.root") }}
              {{- fail "alluxio.dora.client.ufs.root must be set for AlluxioFuse to work." }}
            {{- end }} 
            - {{ get .Values.properties "alluxio.dora.client.ufs.root" }}
            - /mnt/alluxio-fuse
            {{- range .Values.fuse.mountOptions }}
            - -o {{ . }}
            {{- end }}
          env:
            - name: ALLUXIO_CLIENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            {{- range $key, $value := .Values.fuse.env }}
            - name: "{{ $key }}"
              value: "{{ $value }}"
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ $fullName }}-alluxio-env
          securityContext:
            privileged: true
          volumeMounts:
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: {{ $fullName }}-alluxio-conf
              mountPath: /opt/alluxio/conf
            {{- if .Values.secrets }}
{{- include "alluxio.volumeMounts" (dict "volumeMounts" .Values.secrets.fuse "readOnly" true) | indent 12 }}
            {{- end }}
            {{- if .Values.configMaps }}
{{- include "alluxio.volumeMounts" (dict "volumeMounts" .Values.configMaps.fuse "readOnly" true) | indent 12 }}
            {{- end }}
            {{- if .Values.pvcMounts }}
{{- include "alluxio.volumeMounts" (dict "volumeMounts" .Values.pvcMounts.fuse "readOnly" false) | indent 12 }}
            {{- end }}
      restartPolicy: Always
      volumes:
        - name: alluxio-fuse-device
          hostPath:
            path: /dev/fuse
            type: CharDevice
        - name: {{ $fullName }}-alluxio-conf
          configMap:
            name: {{ $fullName }}-alluxio-conf
        {{- if .Values.secrets }}
{{- include "alluxio.secretVolumes" .Values.secrets.fuse | indent 8 }}
        {{- end }}
        {{- if .Values.configMaps }}
{{- include "alluxio.configMapVolumes" .Values.configMaps.fuse | indent 8 }}
        {{- end }}
        {{- if .Values.pvcMounts }}
{{- include "alluxio.persistentVolumes" .Values.pvcMounts.fuse | indent 8 }}
        {{- end }}
{{- end }}
