#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{ if .Values.csi.enabled -}}
{{- $name := include "alluxio.name" . }}
{{- $fullName := include "alluxio.fullname" . }}
{{- $chart := include "alluxio.chart" . }}

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ $fullName }}-csi-nodeplugin
  labels:
    name: {{ $fullName }}-csi-nodeplugin
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $fullName }}-csi-nodeplugin
spec:
  selector:
    matchLabels:
      app: {{ $name }}
      role: {{ $fullName }}-csi-nodeplugin
      name: {{ $fullName }}-csi-nodeplugin
  template:
    metadata:
      labels:
        name: {{ $fullName }}-csi-nodeplugin
        app: {{ $name }}
        chart: {{ $chart }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: alluxio-csi-nodeplugin
    spec:
      serviceAccountName: {{ $fullName }}-csi-sa
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy | default (.Values.hostNetwork | ternary "ClusterFirstWithHostNet" "ClusterFirst") }}
      nodeSelector:
        {{- if .Values.csi.nodePlugin.nodeSelector }}
{{ toYaml .Values.fuse.nodeSelector | trim | indent 8 }}
      {{- else if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | trim | indent 8 }}
      {{- end }}
      tolerations:
      {{- if .Values.csi.nodePlugin.tolerations }}
{{ toYaml .Values.fuse.tolerations | trim | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | trim | indent 8 }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
{{ include "alluxio.imagePullSecrets" . | indent 6 }}
      {{- end}}
      {{- if .Values.imagePullSecrets }}
{{ include "alluxio.imagePullSecrets" . | indent 6 }}
      {{- end}}
      containers:
        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.0.0
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/alluxio /registration/alluxio-reg.sock"]
          args:
            - --v=5
            - --csi-address=/plugin/csi.sock
            - --kubelet-registration-path=/var/lib/kubelet/plugins/csi-alluxio-plugin/csi.sock
          {{- if .Values.csi.nodePlugin.driverRegistrar.resources }}
{{ include "alluxio.resources" .Values.csi.nodePlugin.driverRegistrar.resources | indent 10 }}
          {{- end }}
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: registration-dir
              mountPath: /registration
        - name: csi-nodeserver
          securityContext:
            privileged: true
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command: ["tini", "--", "/entrypoint.sh"]
          args :
            - csiserver
            - --v=5
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
          {{- if .Values.csi.nodePlugin.nodeserver.resources  }}
{{ include "alluxio.resources" .Values.csi.nodePlugin.nodeserver.resources | indent 10 }}
          {{- end }}
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CSI_ENDPOINT
              value: unix://plugin/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: pods-mount-dir
              mountPath: /var/lib/kubelet
              mountPropagation: "Bidirectional"
            - name: {{ $fullName }}-csi-fuse-config
              mountPath: /opt/alluxio/integration/kubernetes/csi
      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi-alluxio-plugin
            type: DirectoryOrCreate
        - name: pods-mount-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
          name: registration-dir
        - name: csi-fuse-config
          configMap:
            name: {{ $fullName }}-fuse-config
            items:
              - key: alluxio-fuse-config
                path: alluxio-csi-fuse.yaml
{{- end }}
