#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

apiVersion: batch/v1
kind: Job
metadata:
  name: load-job
  labels:
    role: load-job
    app: alluxio
spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: load-job
      labels:
        role: dataload-pod
        app: alluxio
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      restartPolicy: Never
      containers:
        - name: load
          imagePullPolicy: IfNotPresent
          image: alluxio/k8s-operator-jobs:latest
          env:
            - name: ALLUXIO_CLIENT_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
