#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{- $name := include "alluxio.name" . }}
{{- $fullName := include "alluxio.fullname" . }}
{{- $chart := include "alluxio.chart" . }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-alluxio-load
  labels:
    name: {{ $fullName }}-alluxio-load
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  load.sh: |-
    #!/usr/bin/env bash

    main() {
      if [[ $# != 1 ]]; then
        echo "Load command only takes one argument"
        exit 1
      fi
      exec /opt/alluxio/bin/alluxio fs load $1 --submit
      waitUntilLoadFinished
    }

    waitUntilLoadFinished() {
      while true; do {
        sleep 15
        res=$(/opt/alluxio/bin/alluxio fs load $1 --progress)
        if [[ "${res}" == *"SUCCEEDED"* ]]; then
          exit 0
        elif [[ "${res}" == *"FAILED"* ]]; then
          exit 1
        fi
      }
    }

    main "$@"
