#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{- $name := include "alluxio.name" . }}
{{- $fullName := include "alluxio.fullname" . }}
{{- $chart := include "alluxio.chart" . }}
{{- $workerRoleName := "alluxio-worker"}}
{{ $metastoreVolumeName := include "alluxio.getVolumeName" (dict "prefix" $fullName "component" "metastore") }}
{{ $pagestoreVolumeName := include "alluxio.getVolumeName" (dict "prefix" $fullName "component" "pagestore") }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}-worker
  labels:
    name: {{ $fullName }}-worker
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $workerRoleName }}
spec:
  replicas: {{ .Values.worker.count }}
  selector:
    matchLabels:
      name: {{ $fullName }}-worker
      app: {{ $name }}
      chart: {{ $chart }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: {{ $workerRoleName }}
  template:
    metadata:
      labels:
        name: {{ $fullName }}-worker
        app: {{ $name }}
        chart: {{ $chart }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: {{ $workerRoleName }}
      annotations:
      {{- if .Values.worker.podAnnotations }}
{{- toYaml .Values.worker.podAnnotations | nindent 8 }}
      {{- end }}
      {{- if and .Values.metrics.prometheusMetricsServlet.enabled .Values.metrics.prometheusMetricsServlet.podAnnotations }}
{{- toYaml .Values.metrics.prometheusMetricsServlet.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: {{ .Values.dnsPolicy | default (.Values.hostNetwork | ternary "ClusterFirstWithHostNet" "ClusterFirst") }}
      {{- if .Values.hostAliases }}
{{- include "alluxio.hostAliases" . | nindent 6 }}
      {{- end }}
      nodeSelector:
      {{- if .Values.worker.nodeSelector }}
{{ toYaml .Values.worker.nodeSelector | trim | indent 8  }}
      {{- end }}
      {{- if .Values.nodeSelector }}
{{ toYaml .Values.nodeSelector | trim | indent 8  }}
      {{- end }}
      affinity:
      {{- if .Values.worker.limitOneWorkerPerNode }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "role"
                    operator: In
                    values:
                      - {{ $workerRoleName }}
              topologyKey: "kubernetes.io/hostname"
      {{- end }}
      {{- if .Values.worker.affinity }}
{{- toYaml .Values.worker.affinity | nindent 8 }}
      {{- end }}
      tolerations:
      {{- if .Values.worker.tolerations }}
{{ toYaml .Values.worker.tolerations | trim | indent 8  }}
      {{- end }}
      {{- if .Values.tolerations }}
{{ toYaml .Values.tolerations | trim | indent 8  }}
      {{- end }}
      securityContext:
        runAsUser: {{ .Values.user }}
        runAsGroup: {{ .Values.group }}
        fsGroup: {{ .Values.fsGroup }}
      {{- if .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- end }}
      {{- if .Values.imagePullSecrets }}
{{ include "alluxio.imagePullSecrets" . | indent 6 }}
      {{- end}}
      initContainers:
      - name: wait-master
        image: {{ .Values.image }}:{{ .Values.imageTag }}
        command: [ "/bin/sh", "-c" ]
        args:
          - until nslookup {{ $fullName }}-master-0;
            do sleep 2;
            done
      containers:
        - name: alluxio-worker
          image: {{ .Values.image }}:{{ .Values.imageTag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{- if .Values.worker.resources  }}
{{ include "alluxio.resources" .Values.worker.resources | indent 10 }}
          {{- end }}
          command: ["tini", "--", "/entrypoint.sh"]
          args:
            - worker-only
            - --no-format
          env:
          - name: ALLUXIO_WORKER_HOSTNAME
            valueFrom:
              fieldRef:
                {{- if .Values.hostNetwork }}
                fieldPath: status.hostIP
                {{- else }}
                fieldPath: status.podIP
                {{- end }}
          {{- range $key, $value := .Values.worker.env }}
          - name: "{{ $key }}"
            value: "{{ $value }}"
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: {{ .Values.worker.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.worker.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.worker.readinessProbe.successThreshold }}
          livenessProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: {{ .Values.worker.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.worker.livenessProbe.failureThreshold }}
          startupProbe:
            tcpSocket:
              port: rpc
            initialDelaySeconds: {{ .Values.worker.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.worker.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.worker.startupProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.worker.startupProbe.failureThreshold }}
          ports:
          - containerPort: {{ .Values.worker.ports.rpc }}
            name: rpc
          - containerPort: {{ .Values.worker.ports.web }}
            name: web
          volumeMounts:
            - name: {{ $fullName }}-alluxio-conf
              mountPath: /opt/alluxio/conf
            {{- if .Values.metastore.enabled }}
            - name: {{ $metastoreVolumeName }}
              mountPath: {{ include "alluxio.mount.basePath" "/metastore"}}
            {{- end }}
            {{- if .Values.secrets }}
{{- include "alluxio.volumeMounts" (dict "volumeMounts" .Values.secrets.worker "readOnly" true) | indent 12 }}
            {{- end }}
            {{- if .Values.configMaps }}
{{- include "alluxio.volumeMounts" (dict "volumeMounts" .Values.configMaps.worker "readOnly" true) | indent 12 }}
            {{- end }}
            {{- if .Values.pvcMounts }}
{{- include "alluxio.volumeMounts" (dict "volumeMounts" .Values.pvcMounts.worker "readOnly" false) | indent 12 }}
            {{- end }}
            {{- if .Values.pagestore }}
            - mountPath: {{ include "alluxio.mount.basePath" "/pagestore"}}
              name: {{ $pagestoreVolumeName }}
            {{- end }}
      restartPolicy: Always
      volumes:
        - name: {{ $fullName }}-alluxio-conf
          configMap:
            name: {{ $fullName }}-alluxio-conf
        {{- if .Values.metastore.enabled }}
        - name: {{ $metastoreVolumeName }}
          persistentVolumeClaim:
            claimName: {{ include "alluxio.getPvcName" (dict "prefix" $fullName "component" "metastore") }}
        {{- end }}
        {{- if .Values.secrets }}
{{- include "alluxio.secretVolumes" .Values.secrets.worker | indent 8 }}
        {{- end }}
        {{- if .Values.configMaps }}
{{- include "alluxio.configMapVolumes" .Values.configMaps.worker | indent 8 }}
        {{- end }}
        {{- if .Values.pvcMounts }}
{{- include "alluxio.persistentVolumeClaims" .Values.pvcMounts.worker | indent 8 }}
        {{- end }}
        {{- if .Values.pagestore }}
        {{- if eq .Values.pagestore.type "hostPath"}}
        - name: {{ $pagestoreVolumeName }}
          hostPath:
            path: {{ .Values.pagestore.hostPath }}
            type: Directory
        {{- else if eq .Values.pagestore.type "persistentVolumeClaim" }}
        - name: {{ $pagestoreVolumeName }}
          persistentVolumeClaim:
            claimName: {{ include "alluxio.getPvcName" (dict "prefix" $fullName "component" "pagestore") }}
        {{- else if eq .Values.pagestore.type "emptyDir" }}
        - name: {{ $pagestoreVolumeName }}
          emptyDir:
            sizeLimit: {{ .Values.pagestore.quota }}
            {{- if .Values.pagestore.memoryBacked }}
            medium: "Memory"
            {{- end }}
        {{- end }}
        {{- end }}
