#
# The Alluxio Open Foundation licenses this work under the Apache License, version 2.0
# (the "License"). You may not use this work except in compliance with the License, which is
# available at www.apache.org/licenses/LICENSE-2.0
#
# This software is distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
# either express or implied, as more fully set forth in the License.
#
# See the NOTICE file distributed with this work for information regarding copyright ownership.
#

{{- $name := include "alluxio.name" . }}
{{- $fullName := include "alluxio.fullname" . }}
{{- $chart := include "alluxio.chart" . }}

{{- if eq .Values.pagestore.type "persistentVolumeClaim" }}
{{- $pvcName := include "alluxio.getPvcName" (dict "prefix" $fullName "component" "pagestore") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $pvcName }}
  labels:
    name: {{$pvcName }}
    app: {{ $name }}
    chart: {{ $chart }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  resources:
    requests:
      storage: {{ .Values.pagestore.quota }}
  storageClassName: {{ .Values.pagestore.storageClass }}
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      name: {{ $pvcName }}
      app: {{ $name }}
      chart: {{ $chart }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
{{- end }}
