name: Alluxio Helm Chart Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Run Helm Chart sanity check
        run: tests/helm/test.sh
        timeout-minutes: 5

      - name: Archive result templates
        continue-on-error: true
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: result templates
          path: tests/helm/resultTemplates
          retention-days: 7