name: Alluxio Helm Chart Check

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: Run Helm Chart sanity check
        run: tests/helm/test.sh
        timeout-minutes: 5
